language: python
python: 2.7
env:
  global:
    - IMAGE=pymicro-flask
services:
  - docker
before_install:
  - docker version
  - docker-compose version
before_script:
  - docker-compose -f docker/docker-compose.yml build $IMAGE
  - docker run --rm $IMAGE /bin/bash ./run_test.sh
script:
  - docker-compose -f docker/docker-compose.yml -f docker/test/docker-compose.yml run test
  - docker-compose -f docker/docker-compose.yml -f docker/test/docker-compose.yml down
branches:
  only:
    - master
